import { useMediaQuery } from "@mui/material";
import Head from "next/head";
export default function Home() {
  const isDesktopOrLaptop = useMediaQuery("(min-width:600px)");
  return (
    <div>
      <Head>
        <title>Pizzaria</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>{isDesktopOrLaptop ? <>laptop</> : <>mobile</>}</div>
    </div>
  );
}
